### ISSUE TITLE
Document http commands for HE enabled Tasmota Fw

### ISSUE THREAD

**Issue by cavanaug** [markus-li/Hubitat#18]
Specifically Im looking for how to

- set the Hubitat/Smarthings parameters, ip & port
- enable the Hubitat/Smarthings
- enable Hue Bridge emulation

**Comment by GaryMilne** [comment]
Go to the Tasmota web page. 
Configuration\Other to enable Hubitat/Smartthings and Hue Bridge
Configuration\ Configure Hubitat - Smartthings  to modify Hubitat IP and port but this is configured for you automatically by the device driver and should not need to be changed.

**Comment by cavanaug** [comment]
Gary, im looking to automate the onboarding of devices and using curl cmnd= instructions to script the configuration of my devices to avoid going to a webpage and clicking/cutting/pasting etc.  Tasmota FW itself has a rich set of cmnd's to configure the device over http, so I am looking for the equivalent for the additions made for HE to script those.

**Comment by GaryMilne** [comment]
I misunderstood, but I can still help you. If you go into the web interface and edit the values you can usually figure out the syntax from the URL bar:  Change ip\port http://192.168.0.125/hs?mh=192.168.0.200&ml=39501&save=  (pretty straightforward)

**Turn on Belkin**
http://192.168.0.125/co?t1=%7B%22NAME%22%3A%22SonoffS31%22%2C%22GPIO%22%3A%5B17%2C145%2C0%2C146%2C0%2C0%2C0%2C0%2C21%2C56%2C0%2C0%2C0%5D%2C%22FLAG%22%3A0%2C%22BASE%22%3A41%7D&wp=****&b1=on&h1=on&a0=Gutter+Heater+-+Front**&b2=2&save=**

**Turn off Belkin**
http://192.168.0.125/co?t1=%7B%22NAME%22%3A%22SonoffS31%22%2C%22GPIO%22%3A%5B17%2C145%2C0%2C146%2C0%2C0%2C0%2C0%2C21%2C56%2C0%2C0%2C0%5D%2C%22FLAG%22%3A0%2C%22BASE%22%3A41%7D&wp=****&b1=on&h1=on&a0=Gutter+Heater+-+Front**&b2=0&save=**

See the difference is the b2=2 or b2=0  (b2=1 would be WeMo). 

So you send it "http://192.168.0.125/co?b2=2&save=" would turn Hue Bridge emulation on.

Pretty easy.

**Comment by cavanaug** [comment]
Perfect...

**Comment by markus-li** [comment]
First, this isn't the right place for support, use the HE community thread for that, unless you want to wait for a long time for a response...
The Tasmota commands are:
setoption113 1     // Enables the Hubitat features
HubitatHost <hub ip>   // Example: HubitatHost 192.168.1.1
HubitatPort 39501
Emulation 2      // Hue Bridge Emulation on

For all other Tasmota commands:
https://tasmota.github.io/docs/Commands/

With all that said, all these commands are sent to Tasmota when Configure runs in the driver, if they are not, either you have the wrong firmware on the device or there is a bug that needs to be fixed in the driver. Try pressing Configure on the Parent Device page and all this will be sent to your Tasmota  device again.
After Reset 5 has been issued during install, the default is that Hue Bridge emulation is set when using the Hubitat version of Tasmota. That way the device will be discovered by the Tasmota Device Manager App and the rest of the settings will be set by the driver.

**Comment by cavanaug** [comment]
@markus-li thanks, that is what i was initially looking for.   

But based on your comments, it does look like my system is having problems as no configuration is getting set in tasmota via the Tasmota device manager.

Since you prefer support via HE community thread, Ill move this discussion over there...
